### ISSUE TITLE
WPA on wlan0 not autoconnecting without wlan1 being active

### ISSUE THREAD

**Issue by diveyez** [Re4son/Kali-Pi#11]
It appears that with your kernel, the pi cannot connect to wifi unless I plug in the wlan1 interface into usb. No idea why and I am tired of troubleshooting it.

**Comment by Re4son** [comment]
Not good, thanks for letting me know. Any kali image or just the Sticky Fingers?
The kernel from the repository or manual installation?

**Comment by diveyez** [comment]
It looks like its the nexmon's again bro. Shit hit me during a time when I needed that fresh format lol =)
Still safe. Thank God for VMWorkstation

**Comment by diveyez** [comment]
It’s the nexmon’s ,, I smell a sabotage

**Comment by 3x-M4ch1nA** [comment]
Nexmon is constantly effing with this. Smh. I've also noticed if you have an external wifi plugged in before boot, it designates it as wlan0. So then you can't use mon0up. Idk if that changed. But I think it still behaves this way

**Comment by diveyez** [comment]
There is a major issue with the nexmon drivers period. @Re4son  will need to update his kernel and builds accordingly. This feels like a sabotage because the stuff now works flawless on ParrotOS but only on ParrotOS now.

**Comment by Re4son** [comment]
Can't reproduce it.
Has macchanger maybe kicked in?

**Comment by diveyez** [comment]
Negative, This is likely something happening to USA yankee's as I see that when I am on NZ laws it does not happen anymore.

**Comment by diveyez** [comment]
It works fine if you dont update anything from your base image.
However, we both know there is much needed updates ;)
Id like to see a 2019.2 image set from you if you dont mind! =) Summer is coming. Los Angeles is so close...

**Comment by Re4son** [comment]
Working on it. In a day or two.

**Comment by diveyez** [comment]
One Love =)
I'll shoot some video when I go hunting. White knight to save the day. These kids have no idea how vuln they are with their WiFi's and bluetooths
